import { readFileSync } from 'node:fs';
import { describe, expect, test } from 'vitest';

const architecture = readFileSync('docs/ARCHITECTURE.md', 'utf8');
const maintainerGuide = readFileSync('docs/AI-MAINTAINER.md', 'utf8');
const agentDevEnv = readFileSync('docs/AGENT-DEV-ENV.md', 'utf8');

describe('operator visibility contract', () => {
  test('documents the send-state visibility requirements', () => {
    expect(architecture).toContain('## Operator Visibility Contracts');
    expect(maintainerGuide).toContain('### Operator Visibility');
    for (const phrase of [
      'Dashboard must show whether automatic scheduled sending is ready',
      'Course email schedules define automatic class emails',
      'Class detail must show both automatic course emails',
      'History must provide a complete outbound email history',
      'Test audit navigation is visible only while email test mode is enabled',
      'AI model selection should prefer model discovery'
    ]) {
      expect(architecture).toContain(phrase);
    }
    for (const phrase of [
      'due approved campaign count',
      'next approved send',
      'Approve and schedule the campaign',
      'Campaign detail must',
      'Communications must',
      'approve campaigns',
      'manual send-due control'
    ]) {
      expect(architecture).not.toContain(phrase);
      expect(maintainerGuide).not.toContain(phrase);
      expect(agentDevEnv).not.toContain(phrase);
    }
    expect(agentDevEnv).toContain('next scheduled send');
    expect(agentDevEnv).toContain('automatic course emails');
    expect(maintainerGuide).toContain('`src/routes/scheduled-emails/` owns Scheduled Emails');
    expect(maintainerGuide).toContain('`src/routes/history/` owns History');
    expect(agentDevEnv).toContain('`/history` shows History');
    expect(maintainerGuide).not.toContain('`src/routes/campaigns/` owns Scheduled Emails');
    expect(maintainerGuide).not.toContain('`src/routes/communications/` owns History');
    expect(agentDevEnv).not.toContain('`/communications` shows History');
  });

  test('keeps implementation hooks for documented visibility requirements', () => {
    expect(readFileSync('src/lib/server/page-data.ts', 'utf8')).toContain('schedulerStatus');
    expect(readFileSync('src/lib/server/class-default-campaigns.ts', 'utf8')).toContain('syncDefaultCampaignsForCourseType');
    expect(readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8')).toContain('scheduledCampaigns');
    expect(readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8')).toContain('scheduledCampaignsPage = repo.listCampaignsForClassSession');
    expect(readFileSync('src/routes/settings/+page.server.ts', 'utf8')).toContain('createChecklistItem');
    expect(readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8')).toContain(
      'checklistState: repo.listEnrollmentChecklistState(params.id, detail.roster.map'
    );
    expect(readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8')).toContain('toggleChecklistItem');
    expect(readFileSync('src/lib/server/page-data.ts', 'utf8')).toContain('communicationPage = repo.listCommunicationsPage');
    expect(readFileSync('src/lib/shared/navigation.ts', 'utf8')).toContain('emailTestModeEnabled');
    expect(readFileSync('src/lib/server/llm.ts', 'utf8')).toContain('listAiModels');
  });

  test('keeps risky send actions and approval language off the dashboard', () => {
    const dashboard = readFileSync('src/routes/+page.svelte', 'utf8');
    const dashboardServer = readFileSync('src/routes/+page.server.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');
    expect(dashboard).not.toContain('resendFailedToday');
    expect(dashboardServer).not.toContain('resendFailedToday');
    expect(dashboard).not.toContain('Resend failed today');
    expect(dashboard).not.toContain('approved due now');
    expect(dashboard).not.toContain('No upcoming approved sends');
    expect(dashboard).not.toContain('failed today');
    expect(dashboard).not.toContain('ready to send now');
    expect(dashboard).not.toContain('<p>Ready to send</p>');
    expect(dashboard).toContain('<p>Scheduled Emails</p>');
    expect(dashboard).toContain('<a href="/scheduled-emails"><span>{data.stats.campaigns}</span><p>Scheduled Emails</p></a>');
    expect(dashboard).not.toContain('<a href="/scheduled-emails"><span>{data.stats.pendingDeliveries}</span><p>Scheduled Emails</p></a>');
    expect(dashboard).not.toContain('<p>Prepared scheduled emails</p>');
    expect(dashboard).not.toContain('<p>Recipient emails prepared</p>');
    expect(dashboard).not.toContain('<div class="status-row">');
    expect(dashboard).not.toContain('>Campaigns<');
    expect(dashboard).not.toContain('Manage campaigns');
    expect(dashboard).toContain('>View scheduled emails</a>');
    expect(dashboard).not.toContain('>Manage scheduled emails</a>');
    expect(dashboard).not.toContain("'Approved'");
    expect(dashboard).toContain('Attention needed');
    expect(dashboard).toContain('Scheduled sending');
    expect(dashboard).toContain('data.schedulerStatus.dueReadyCount');
    expect(dashboard).toContain('data.schedulerStatus.nextReady');
    expect(dashboard).toContain("scheduled email{data.schedulerStatus.dueReadyCount === 1 ? '' : 's'} ready to send");
    expect(dashboard).toContain('No upcoming scheduled email ready to send');
    expect(dashboard).not.toContain('ready scheduled email');
    expect(dashboard).not.toContain('No upcoming ready scheduled email');
    expect(dashboard).toContain('Next scheduled send');
    expect(dashboard).toContain('Scheduled Emails');
    expect(dashboard).toContain('<h2>Recent scheduled emails</h2>');
    expect(dashboard).not.toContain('<h2>Recent schedules</h2>');
    expect(dashboard).toContain('No scheduled emails yet.');
    expect(dashboard).not.toContain('No class emails scheduled.');
    expect(dashboard).toContain('Failed emails');
    expect(dashboard).not.toContain('Failed email history');
    expect(dashboard).toContain('href="/history?status=failed"');
    expect(dashboard).not.toContain('href="/history?search=failed"');
    expect(dashboard).not.toContain('Fix failed emails');
    expect(dashboard).not.toContain('need attention before retrying');
    expect(dashboard).not.toContain('need review before retrying');
    expect(dashboard).toContain('View failed sends in History before retrying from the scheduled email detail page.');
    expect(dashboard).toContain('email issue');
    expect(dashboard).toContain('data.recentScheduledEmails');
    expect(dashboard).toContain('dashboardReturnTo');
    expect(dashboard).toContain('href={`/scheduled-emails/${campaign.id}?returnTo=${encodeURIComponent(dashboardReturnTo)}`}');
    expect(dashboard).not.toContain('scheduledEmailStatusLabel(campaign.readyToSend)');
    expect(dashboard).not.toContain('class:good={campaign.readyToSend}');
    expect(dashboard).not.toContain('campaign.approved');
    expect(pageData).not.toContain('campaign.approved');
    expect(pageData).toContain('isReadyToSend(campaign)');
    expect(dashboard).not.toContain("campaign.approved ? 'Scheduled' : 'Draft'");
    expect(pageData).toContain('const { approved, ...visibleCampaign } = campaign;');
    expect(pageData).toContain('withVisibleScheduledEmailsPage(campaignsPage)');
    expect(pageData).toContain('nextReady: scheduledEmailStatus.nextReady ? withReadyToSend(scheduledEmailStatus.nextReady) : undefined');
    expect(pageData).toContain('recentScheduledEmails');
    expect(pageData).toContain('countReadyScheduledEmailsDue');
    expect(pageData).toContain('getNextReadyScheduledEmail');
    expect(pageData).not.toContain('const campaigns = repo.listCampaigns()');
  });

  test('removes retired busy-page layout helpers from the shared stylesheet', () => {
    const styles = readFileSync('src/styles.css', 'utf8');

    expect(styles).not.toContain('.two-column');
    expect(styles).not.toContain('.status-row');
    expect(styles).not.toContain('.token-help');
  });

  test('keeps contact detail focused on recent email activity with a filtered History link', () => {
    const contacts = readFileSync('src/routes/contacts/+page.svelte', 'utf8');
    const contactsServer = readFileSync('src/routes/contacts/+page.server.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');
    expect(contacts).not.toContain('Reusable student contacts');
    expect(contacts).not.toContain('<p class="eyebrow">People</p>');
    expect(contacts).toContain('<p class="eyebrow">Contacts</p>');
    expect(contacts).toContain('<h2>Students and email recipients</h2>');
    expect(contacts).toContain('Recent emails');
    expect(contacts).toContain('contactDetailReturnTo');
    expect(contacts).toContain('href={`/classes/${item.classSessionId}?returnTo=${encodeURIComponent(contactDetailReturnTo)}`}');
    expect(contacts).toContain('View all in History');
    expect(contacts).toContain('/history?contactId=');
    expect(contacts).toContain('href={`${contactHistoryHref}&returnTo=${encodeURIComponent(contactDetailReturnTo)}`}');
    expect(contacts).toContain('contactHistoryHref');
    expect(contacts).toContain('returnTo=${encodeURIComponent(contactHistoryHref)}');
    expect(contacts).toContain('href={`/history/${communication.id}?returnTo=${encodeURIComponent(contactHistoryHref)}`}');
    expect(contacts).toContain('data.actionMessage');
    expect(contacts).toContain('{#if contactsSearch}<input name="search" type="hidden" value={contactsSearch} />{/if}');
    expect(contacts).toContain('{#if currentContactsPage > 1}<input name="page" type="hidden" value={currentContactsPage} />{/if}');
    expect(contacts).toContain("communication.source === 'campaign' ? 'Scheduled email' : 'Direct email'");
    expect(contacts).toContain('replySummary({ replyCount: communication.replyCount, unhandledReplyCount: communication.unhandledReplyCount })');
    expect(contacts).not.toContain('communication.unreviewedReplyCount');
    expect(contacts).not.toContain('· {communication.source}');
    expect(contacts).not.toContain('Email activity');
    expect(contacts).not.toContain('Select a student to view class history and recent emails.');
    expect(contacts).toContain('Search contacts');
    expect(contacts).toContain('contactsPageHref');
    expect(contacts).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(contacts).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(contacts).toContain('href={contactsClearHref}');
    expect(contacts).toContain('contactsListReturnTo');
    expect(contacts).toContain('href={`/contacts?action=add&returnTo=${encodeURIComponent(contactsListReturnTo)}`}');
    expect(contacts).toContain('href={`/contacts?action=import&returnTo=${encodeURIComponent(contactsListReturnTo)}`}');
    expect(contacts).toContain('href={`/contacts?action=image&returnTo=${encodeURIComponent(contactsListReturnTo)}`}');
    expect(contacts).toContain('href={`/contacts?contactId=${contact.id}&returnTo=${encodeURIComponent(contactsListReturnTo)}`}');
    expect(contacts).toContain('<input name="csvFile" type="file"');
    expect(contacts).toContain('<input name="imageFile" type="file"');
    expect(contacts).toContain("href={data.returnTo || '/contacts'}");
    expect(contacts).not.toContain('href="/contacts">Cancel');
    expect(contacts).toContain('Page {currentContactsPage} of {totalContactsPages}');
    expect(contacts.indexOf('<div class="list">')).toBeLessThan(contacts.indexOf('<div class="form-stack task-stack">'));
    expect(contacts).not.toContain('<section class="band two-column">');
    expect(contactsServer).toContain('page: Number(url.searchParams.get');
    expect(contactsServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(contactsServer).toContain('contactActionReturn');
    expect(contactsServer).toContain('throw redirect(303, contactActionReturn(form,');
    expect(contactsServer).toContain("throw redirect(303, contactActionReturn(form, 'Choose a CSV file to import.'))");
    expect(contactsServer).toContain('throw redirect(303, contactActionReturn(form, `Imported contacts:');
    expect(contactsServer).toContain("throw redirect(303, contactActionReturn(form, 'Choose an image to import.'))");
    expect(contactsServer).toContain('throw redirect(303, contactActionReturn(form, `Imported screenshot contacts:');
    expect(pageData).toContain('contactsPage = repo.listContactsPage');
  });

  test('keeps Classes focused on selecting scheduled classes, not setup data', () => {
    const classes = readFileSync('src/routes/classes/+page.svelte', 'utf8');
    const classesServer = readFileSync('src/routes/classes/+page.server.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');
    expect(classes).toContain('<h2>Scheduled classes</h2>');
    expect(classes).toContain('Open class');
    expect(classes).not.toContain('href={`/classes/${session.id}`}');
    expect(classes).not.toContain('Course types and scheduled classes');
    expect(classes).not.toContain('Class management views');
    expect(classes).not.toContain('Checklist defaults');
    expect(classes).not.toContain('Add course type');
    expect(classes).not.toContain('Enroll student');
    expect(classes).not.toContain('Manage class setup');
    expect(classes).not.toContain('defaults.');
    expect(classes).not.toContain('<h3>Class details</h3>');
    expect(classes).not.toContain('Select a class to manage its roster, requirements, and scheduled emails.');
    expect(classesServer).not.toContain('checklistItems: repo.listChecklistItems()');
    expect(classesServer).not.toContain('selectedCourseDefaults');
    expect(classesServer).not.toContain('createCourse:');
    expect(classesServer).not.toContain('createLocation:');
    expect(classesServer).not.toContain('saveCourseDefaults:');
    expect(classes).toContain('Manage courses, locations, and prep tasks');
    expect(classes).toContain('addLabel="Add course"');
    expect(classes).toContain('addLabel="Add location"');
    expect(classes).toContain('addHref={appDataAddHref}');
    expect(classes).toContain('href={appDataAddHref}');
    expect(classes).not.toContain('href="/settings?section=app-data">Manage courses, locations, and prep tasks</a>');
    expect(classes).toContain('Search classes');
    expect(classes).toContain('classesPageHref');
    expect(classes).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(classes).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(classes).toContain('href={classesClearHref}');
    expect(classes).toContain('classesListReturnTo');
    expect(classes).toContain('classWorkflowReturnTo');
    expect(classes).toContain('addClassReturnTo');
    expect(classes).toContain('href={`/classes?action=session&returnTo=${encodeURIComponent(classesListReturnTo)}`}');
    expect(classes).toContain('href={`/classes/${session.id}?returnTo=${encodeURIComponent(classesListReturnTo)}`}');
    expect(classes).toContain("href={data.returnTo || '/classes'}");
    expect(classes).not.toContain('href="/classes?action=session">Add class');
    expect(classes).not.toContain('href="/classes">Cancel');
    expect(classes).toContain('data.actionMessage');
    expect(classes).toContain('{#if classesSearch}<input name="search" type="hidden" value={classesSearch} />{/if}');
    expect(classes).toContain('{#if currentClassesPage > 1}<input name="page" type="hidden" value={currentClassesPage} />{/if}');
    expect(classes).toContain('Page {currentClassesPage} of {totalClassesPages}');
    expect(classes).not.toContain('<section class="band two-column">');
    expect(classesServer).toContain('page: Number(url.searchParams.get');
    expect(classesServer).toContain('localReturnTo');
    expect(classesServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(classesServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(classesServer).toContain('classActionReturn');
    expect(classesServer).toContain('throw redirect(303, classActionReturn(form,');
    expect(classesServer).toContain('Created ${defaultCampaignCount} scheduled email');
    expect(classesServer).not.toContain('Scheduled ${defaultCampaignCount} course email');
    expect(pageData).toContain('classSessionsPage = repo.listClassSessionsPage');
  });

  test('makes class detail roster prep understandable without checklist jargon', () => {
    const classDetail = readFileSync('src/routes/classes/[id]/+page.svelte', 'utf8');
    const classDetailServer = readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8');

    expect(classDetail).toContain('Roster and prep');
    expect(classDetail).toContain("href={data.returnTo || '/classes'}");
    expect(classDetailServer).toContain('localReturnTo');
    expect(classDetailServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(classDetailServer).toContain('Created ${defaultCampaignCount} scheduled email');
    expect(classDetailServer).not.toContain('Scheduled ${defaultCampaignCount} course email');
    expect(classDetail).toContain('Search students');
    expect(classDetail).toContain('data.rosterPage.total');
    expect(classDetail).toContain('rosterPageHref');
    expect(classDetail).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(classDetail).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(classDetail).toContain('data.actionMessage');
    expect(classDetail).toContain('{#if rosterSearch}<input name="search" type="hidden" value={rosterSearch} />{/if}');
    expect(classDetail).toContain('{#if currentRosterPage > 1}<input name="page" type="hidden" value={currentRosterPage} />{/if}');
    expect(classDetail).toContain('{#if data.scheduledCampaignsPage.search}<input name="emailSearch" type="hidden" value={data.scheduledCampaignsPage.search} />{/if}');
    expect(classDetail).toContain('{#if currentClassEmailsPage > 1}<input name="emailPage" type="hidden" value={currentClassEmailsPage} />{/if}');
    expect(classDetail).toContain('Prep items');
    expect(classDetail).toContain('student-prep-items');
    expect(classDetail).toContain('<h3>Import CSV roster</h3>');
    expect(classDetail).toContain('<h3>Import roster photo</h3>');
    expect(classDetail).toContain('<input name="csvFile" type="file"');
    expect(classDetail).toContain('<input name="imageFile" type="file"');
    expect(classDetail).not.toContain('<summary>Import CSV roster</summary>');
    expect(classDetail).not.toContain('<summary>Import roster photo</summary>');
    expect(classDetailServer).toContain('Prep item updated.');
    expect(classDetailServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(classDetailServer).toContain('classDetailActionReturn');
    expect(classDetailServer).toContain('throw redirect(303, classDetailActionReturn(params.id, form,');
    expect(classDetailServer).toContain("throw redirect(303, classDetailActionReturn(params.id, form, 'Choose a CSV file to import.'))");
    expect(classDetailServer).toContain('throw redirect(303, classDetailActionReturn(params.id, form, `Imported roster:');
    expect(classDetailServer).toContain("throw redirect(303, classDetailActionReturn(params.id, form, 'Choose an image to import.'))");
    expect(classDetailServer).toContain('throw redirect(303, classDetailActionReturn(params.id, form, `Imported image roster:');
    expect(classDetailServer).toContain('detail.roster.map((contact) => contact.id)');
    expect(classDetailServer).toContain('repo.listEnrollmentChecklistState(params.id, detail.roster.map');
    expect(classDetailServer).not.toContain('Checklist updated.');
    expect(classDetail).not.toContain('<section class="band two-column">');
  });

  test('keeps class email as a visible primary action instead of a one-item collapse', () => {
    const classDetail = readFileSync('src/routes/classes/[id]/+page.svelte', 'utf8');
    const classDetailServer = readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8');

    expect(classDetail).toContain('<h3>Create scheduled email</h3>');
    expect(classDetail).toContain('Preview student emails');
    expect(classDetail).toContain('<h3>Scheduled email preview</h3>');
    expect(classDetail).toContain('Will create {form.previews.filter((preview) => !preview.skipped).length} scheduled emails, one to each student.');
    expect(classDetail).toContain('<button type="submit">Create scheduled emails</button>');
    expect(classDetail).not.toContain('<h3>Email this class</h3>');
    expect(classDetail).not.toContain('<h3>Student email preview</h3>');
    expect(classDetail).not.toContain('Will schedule {form.previews.filter((preview) => !preview.skipped).length} private emails');
    expect(classDetail).not.toContain('<button type="submit">Schedule individual emails</button>');
    expect(classDetail).not.toContain('<h3>Preview</h3>');
    expect(classDetail).not.toContain('<summary>Email this class</summary>');
    expect(classDetail).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(classDetail).toContain('{#if rosterSearch}<input name="search" type="hidden" value={rosterSearch} />{/if}');
    expect(classDetail).toContain('{#if currentRosterPage > 1}<input name="page" type="hidden" value={currentRosterPage} />{/if}');
    expect(classDetail).toContain('{#if data.scheduledCampaignsPage.search}<input name="emailSearch" type="hidden" value={data.scheduledCampaignsPage.search} />{/if}');
    expect(classDetail).toContain('{#if currentClassEmailsPage > 1}<input name="emailPage" type="hidden" value={currentClassEmailsPage} />{/if}');
    expect(classDetail).toContain('{#if form?.returnTo}<input name="returnTo" type="hidden" value={form.returnTo} />{/if}');
    expect(classDetail).toContain('{#if form?.search}<input name="search" type="hidden" value={form.search} />{/if}');
    expect(classDetail).toContain('{#if form?.page}<input name="page" type="hidden" value={form.page} />{/if}');
    expect(classDetail).toContain('{#if form?.emailSearch}<input name="emailSearch" type="hidden" value={form.emailSearch} />{/if}');
    expect(classDetail).toContain('{#if form?.emailPage}<input name="emailPage" type="hidden" value={form.emailPage} />{/if}');
    expect(classDetailServer).toContain("returnTo: text(form, 'returnTo')");
    expect(classDetailServer).toContain("throw redirect(303, classDetailActionReturn(params.id, form, 'Scheduled email created.'))");
    expect(classDetailServer).toContain("Preview this scheduled email before creating it.");
    expect(classDetailServer).toContain('Resolve missing template variables before creating this scheduled email.');
    expect(classDetailServer).not.toContain('Resolve missing template variables before scheduling.');
    expect(classDetailServer).not.toContain("Class email scheduled.");
    expect(classDetailServer).not.toContain("Preview this class email before scheduling it.");
  });

  test('names inherited class emails without default or class-type jargon', () => {
    const classDetail = readFileSync('src/routes/classes/[id]/+page.svelte', 'utf8');
    const classesServer = readFileSync('src/routes/classes/+page.server.ts', 'utf8');
    const classDetailServer = readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8');

    expect(classDetail).toContain('Automatic scheduled emails');
    expect(classDetail).toContain('Emails added automatically');
    expect(classDetail).toContain('These scheduled emails are created automatically for this class.');
    expect(classDetail).toContain('No automatic scheduled emails are configured for this class.');
    expect(classDetail).toContain('Scheduled emails for this class');
    expect(classDetail).not.toContain('What will send for this class');
    expect(classDetail).toContain('Automatic');
    expect(classDetail).not.toContain('From course');
    expect(classDetail).toContain('Added for this class');
    expect(classDetail).not.toContain('Course email defaults');
    expect(classDetail).not.toContain('Automatic class emails');
    expect(classDetail).not.toContain('Changing course emails');
    expect(classDetail).not.toContain('No automatic emails are configured for this course.');
    expect(classDetail).not.toContain('Automatic schedules from this class type');
    expect(classDetail).not.toContain('Inherited from course type');
    expect(classDetail).not.toContain('Manual schedule');
    expect(classDetail).not.toContain('<span class="pill">Default</span>');
    expect(classDetail).not.toContain('course setup');
    expect(classDetail).not.toContain('setup emails');
    expect(classesServer).toContain('Created ${defaultCampaignCount} scheduled email');
    expect(classesServer).not.toContain('course email');
    expect(classesServer).not.toContain('Course email defaults updated.');
    expect(classesServer).not.toContain('default email');
    expect(classDetailServer).toContain('Class updated. Created');
    expect(classDetailServer).toContain('scheduled email');
    expect(classDetailServer).toContain('`${templateName} scheduled email`');
    expect(classDetailServer).not.toContain('`${templateName} class email`');
    expect(classDetailServer).not.toContain('course email');
    expect(classDetailServer).not.toContain('default email');
  });

  test('gives setup data a clear Settings home', () => {
    const settings = readFileSync('src/routes/settings/+page.svelte', 'utf8');
    const settingsServer = readFileSync('src/routes/settings/+page.server.ts', 'utf8');
    const classesServer = readFileSync('src/routes/classes/+page.server.ts', 'utf8');
    expect(settings).toContain('<summary>Courses, Locations, and Prep Tasks</summary>');
    expect(settings).toContain('<p class="eyebrow">Class setup</p>');
    expect(settings).toContain('Course types');
    expect(settings).toContain('Locations');
    expect(settings).toContain('Prep tasks');
    expect(settings).toContain('Search class setup');
    expect(settings).not.toContain('<summary>App Data</summary>');
    expect(settings).not.toContain('<p class="eyebrow">App data</p>');
    expect(settings).toContain('appDataPageHref');
    expect(settings).toContain('appDataClearHref');
    expect(settings).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(settings).toContain('{#if data.returnTo}<input type="hidden" name="returnTo" value={data.returnTo} />{/if}');
    expect(settings).toContain('href={appDataClearHref}');
    expect(settings).not.toContain('href="/settings?section=app-data">Clear</a>');
    expect(settings).toContain('Page {currentAppDataPage} of {totalAppDataPages}');
    expect(settings).not.toContain('Reusable setup');
    expect(settings).not.toContain('Class prep defaults');
    expect(settings).not.toContain('No class prep defaults yet.');
    expect(settings).toContain('?/createCourse');
    expect(settings).toContain('?/createLocation');
    expect(settings).toContain('?/createChecklistItem');
    expect(settings).toContain('{#if appDataSearch}<input type="hidden" name="appDataSearch" value={appDataSearch} />{/if}');
    expect(settings).toContain('{#if currentAppDataPage > 1}<input type="hidden" name="appDataPage" value={currentAppDataPage} />{/if}');
    expect(settingsServer).toContain("appDataSearch: url.searchParams.get('appDataSearch') ?? ''");
    expect(settings).toContain('name="section" value="app-data"');
    expect(settingsServer).toContain("appDataPage: Number(url.searchParams.get('appDataPage') ?? '1')");
    expect(settingsServer).toContain('settingsAppDataActionReturn');
    expect(settingsServer).toContain("params.set('section', 'app-data')");
    expect(settingsServer).toContain("params.set('appDataSearch', search)");
    expect(settingsServer).toContain("params.set('appDataPage', String(page))");
    expect(settingsServer).toContain('throw redirect(303, settingsAppDataActionReturn(form,');
    expect(readFileSync('src/lib/server/page-data.ts', 'utf8')).toContain('courseTypesPage = repo.listCourseTypesPage');
    expect(readFileSync('src/lib/server/page-data.ts', 'utf8')).toContain('locationsPage = repo.listLocationsPage');
    expect(readFileSync('src/lib/server/page-data.ts', 'utf8')).toContain('checklistItemsPage = repo.listChecklistItemsPage');
    expect(settingsServer).toContain('Prep task added.');
    expect(settingsServer).toContain('Prep task updated.');
    expect(settingsServer).toContain('Prep task deleted.');
    expect(settingsServer).not.toContain('Checklist item added.');
    expect(settingsServer).not.toContain('Checklist item updated.');
    expect(settingsServer).not.toContain('Checklist item deleted.');
    expect(classesServer).not.toContain('Prep task added.');
    expect(classesServer).not.toContain('Prep task updated.');
    expect(classesServer).not.toContain('Prep task deleted.');
  });

  test('uses plain scheduled-email language instead of approval campaign copy', () => {
    const scheduledEmails = readFileSync('src/routes/scheduled-emails/+page.svelte', 'utf8');
    const scheduledEmailsServer = readFileSync('src/routes/scheduled-emails/+page.server.ts', 'utf8');
    const scheduledEmailDetailServer = readFileSync('src/routes/scheduled-emails/[id]/+page.server.ts', 'utf8');
    const scheduledEmailRepository = readFileSync('src/lib/server/repository/campaigns.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');
    const scheduledEmailDetail = readFileSync('src/routes/scheduled-emails/[id]/+page.svelte', 'utf8');
    const classDetail = readFileSync('src/routes/classes/[id]/+page.svelte', 'utf8');
    const settings = readFileSync('src/routes/settings/+page.svelte', 'utf8');

    for (const source of [scheduledEmails, scheduledEmailDetail, classDetail, settings]) {
      expect(source).not.toContain('Approved');
      expect(source).not.toContain('approved campaigns');
      expect(source).not.toContain('approved scheduled campaigns');
    }
    expect(settings).toContain('Let agents schedule confirmed emails');
    expect(settings).toContain('Let agents prepare emails for my confirmation');
    expect(settings).not.toContain('Let agents prepare emails for my review');
    expect(settings).not.toContain('Let agents schedule reviewed emails');
    expect(scheduledEmailDetail).not.toContain('Campaign detail');
    expect(scheduledEmailDetail).not.toContain('· Campaign');
    expect(scheduledEmailDetail).not.toContain('<div class="status-row">');
    expect(scheduledEmailDetail).toContain('<dl class="detail-facts">');
    expect(scheduledEmailDetail).toContain('<dt>Send readiness</dt>');
    expect(scheduledEmailDetail).not.toContain('<dt>Status</dt>');
    expect(scheduledEmailDetail).toContain('<dt>Class</dt>');
    expect(scheduledEmailDetail).toContain('<dt>Template</dt>');
    expect(scheduledEmailDetail).toContain('<dt>Send time</dt>');
    expect(scheduledEmailDetail).toContain('scheduledEmailDetailReturnTo');
    expect(scheduledEmailDetail).toContain('href={`/classes/${data.campaign.classSessionId}?returnTo=${encodeURIComponent(scheduledEmailDetailReturnTo)}`}');
    expect(scheduledEmailDetail).toContain('href={`/templates?templateId=${data.campaign.templateId}&returnTo=${encodeURIComponent(scheduledEmailDetailReturnTo)}`}');
    expect(scheduledEmailDetail).toContain('Scheduled email detail');
    expect(scheduledEmailDetail).toContain('View in History');
    expect(scheduledEmailDetail).toContain('href={`/history?sourceId=${data.campaign.id}&returnTo=${encodeURIComponent(scheduledEmailDetailReturnTo)}`}');
    expect(scheduledEmails).toContain('scheduledEmailReturnTo');
    expect(scheduledEmails).toContain('returnTo=${encodeURIComponent(scheduledEmailReturnTo)}');
    expect(scheduledEmails).toContain('href={`/scheduled-emails?action=preview&returnTo=${encodeURIComponent(scheduledEmailReturnTo)}`}');
    expect(scheduledEmails).not.toContain('href={`/scheduled-emails?action=schedule&returnTo=${encodeURIComponent(scheduledEmailReturnTo)}`}');
    expect(scheduledEmails).toContain("href={data.returnTo || '/scheduled-emails'}");
    expect(scheduledEmails).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(scheduledEmails).toContain('href={`/scheduled-emails/${campaign.id}?returnTo=${encodeURIComponent(scheduledEmailReturnTo)}`}');
    expect(scheduledEmailDetail).toContain("href={data.returnTo || '/scheduled-emails'}");
    expect(scheduledEmailDetailServer).toContain('localReturnTo');
    expect(scheduledEmailDetailServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(scheduledEmailDetail).toContain('Ready to send');
    expect(scheduledEmails).toContain('scheduledEmailStatusLabel(campaign.readyToSend)');
    expect(scheduledEmails).toContain('class:good={campaign.readyToSend}');
    expect(scheduledEmails).toContain('scheduledEmailDeliverySummary(campaign)');
    expect(scheduledEmailDetail).toContain('scheduledEmailStatusLabel(data.campaign.readyToSend)');
    expect(scheduledEmailDetail).toContain('class:good={data.campaign.readyToSend}');
    expect(classDetail).toContain('scheduledEmailStatusLabel(campaign.readyToSend)');
    expect(classDetail).toContain('class:good={campaign.readyToSend}');
    expect(scheduledEmails).not.toContain('campaign.approved');
    expect(scheduledEmailDetail).not.toContain('data.campaign.approved');
    expect(classDetail).not.toContain('campaign.approved');
    expect(scheduledEmailsServer).not.toContain('approved:');
    expect(scheduledEmailDetailServer).not.toContain('approved:');
    expect(scheduledEmailDetailServer).not.toContain('current.approved');
    expect(readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8')).not.toContain('approved: true');
    expect(readFileSync('src/lib/server/class-default-campaigns.ts', 'utf8')).not.toContain('approved: true');
    expect(readFileSync('src/lib/server/class-default-campaigns.ts', 'utf8')).toContain('readyToSend: true');
    expect(scheduledEmails).not.toContain("campaign.approved ? 'Scheduled' : 'Draft'");
    expect(scheduledEmailDetail).not.toContain("data.campaign.approved ? 'Ready to send' : 'Draft'");
    expect(classDetail).not.toContain("campaign.approved ? 'Ready to send' : 'Draft'");
    expect(scheduledEmailDetail).not.toContain('name="approved"');
    expect(scheduledEmailDetail).not.toContain('name="scheduleMode" type="hidden" value="draft"');
    expect(scheduledEmailDetail).toContain('<h3>Edit schedule</h3>');
    expect(scheduledEmailDetail).toContain('<h3>Email content</h3>');
    expect(scheduledEmailDetail).not.toContain('<h3>Template snapshot</h3>');
    expect(scheduledEmailDetail).toContain('Delete scheduled email');
    expect(scheduledEmailDetail).toContain('Emails that have not been sent will be removed.');
    expect(scheduledEmailDetail).not.toContain('delivery rows');
    expect(scheduledEmailDetail).not.toContain('Delete draft');
    expect(scheduledEmailDetail).not.toContain('Draft emails need a student preview before they can be marked ready.');
    expect(scheduledEmailDetail).toContain('Emails needing preview must be previewed with the current roster before they can be marked ready.');
    expect(scheduledEmailDetail).not.toContain('<h3>Lifecycle</h3>');
    expect(scheduledEmailDetail).not.toContain('<section class="band two-column">');
    expect(scheduledEmailDetail).not.toContain('<summary>Template snapshot</summary>');
    expect(scheduledEmailDetail).not.toContain('preview-backed scheduling flow');
    expect(scheduledEmailsServer).toContain("scheduleMode === 'ready'");
    expect(scheduledEmailsServer).not.toContain("form.get('approved') === 'on'");
    expect(scheduledEmails).toContain('Search scheduled emails');
    expect(scheduledEmails).toContain('<h2>Scheduled emails</h2>');
    expect(scheduledEmails).not.toContain('<h2>Manage scheduled emails</h2>');
    expect(scheduledEmails).toContain('Filter scheduled emails');
    expect(scheduledEmails).toContain('statusFilters');
    expect(scheduledEmails).toContain('statusFilterHref');
    expect(scheduledEmails).toContain('aria-label="Filter scheduled emails"');
    expect(scheduledEmails).not.toContain('<select name="status"');
    expect(scheduledEmails).toContain('Upcoming');
    expect(scheduledEmails).toContain('Sent');
    expect(scheduledEmails).toContain('Needs attention');
    expect(scheduledEmails).toContain("value: 'needs_preview', label: 'Needs preview'");
    expect(scheduledEmails).not.toContain("value: 'draft', label: 'Draft'");
    expect(scheduledEmails).not.toContain("label: 'Needs review'");
    expect(scheduledEmails).toContain("value: 'needs_attention', label: 'Needs attention'");
    expect(scheduledEmails).not.toContain("value: 'needs_review'");
    expect(readFileSync('src/lib/server/repository/campaigns.ts', 'utf8')).not.toContain("input.status === 'needs_review'");
    expect(readFileSync('src/lib/server/repository/campaigns.ts', 'utf8')).not.toContain("input.status === 'draft'");
    expect(scheduledEmails).toContain('data.campaignsPage.status');
    expect(scheduledEmails).toContain('campaignsPageHref');
    expect(scheduledEmails).toContain('Create scheduled email');
    expect(scheduledEmails).not.toContain('<button type="submit">Create schedule</button>');
    expect(scheduledEmails).toContain('No scheduled emails yet.');
    expect(scheduledEmails).not.toContain('No class emails scheduled.');
    expect(scheduledEmails).toContain('<h3>Preview scheduled email</h3>');
    expect(scheduledEmails).toContain('<h3>Scheduled email preview</h3>');
    expect(scheduledEmails).toContain('<h3>Choose send time</h3>');
    expect(scheduledEmails).not.toContain('<h3>Schedule this preview</h3>');
    expect(scheduledEmails).not.toContain('<h3>Preview</h3>');
    expect(scheduledEmails).not.toContain('Preview class email');
    expect(scheduledEmails).not.toContain('Schedule class email');
    expect(scheduledEmails).not.toContain('action=schedule');
    expect(scheduledEmails).not.toContain('Create draft schedule');
    expect(scheduledEmails).not.toContain('Draft schedules are not sent.');
    expect(scheduledEmails).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(scheduledEmails).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(scheduledEmails).toContain('data.actionMessage');
    expect(scheduledEmailsServer).toContain('Preview this scheduled email before creating it.');
    expect(scheduledEmailsServer).toContain('Resolve missing template variables before creating this scheduled email.');
    expect(scheduledEmailsServer).not.toContain('ready schedule');
    expect(scheduledEmails).toContain('{#if campaignsSearch}<input name="search" type="hidden" value={campaignsSearch} />{/if}');
    expect(scheduledEmails).toContain('{#if campaignsStatus}<input name="status" type="hidden" value={campaignsStatus} />{/if}');
    expect(scheduledEmails).toContain('{#if currentCampaignsPage > 1}<input name="page" type="hidden" value={currentCampaignsPage} />{/if}');
    expect(scheduledEmails).toContain('Page {currentCampaignsPage} of {totalCampaignsPages}');
    expect(scheduledEmails.indexOf('<div class="list">')).toBeLessThan(scheduledEmails.indexOf('<div class="form-stack">'));
    expect(scheduledEmails).not.toContain('<section class="band two-column">');
    expect(scheduledEmailDetail).toContain('Search recipients');
    expect(scheduledEmailDetail).toContain('data.recipientPage.total');
    expect(scheduledEmailDetail).toContain('recipientPageHref');
    expect(scheduledEmailDetail).toContain('scheduledEmailDetailReturnTo');
    expect(scheduledEmailDetail).toContain('name="returnTo" value={data.returnTo}');
    expect(scheduledEmailDetail).toContain('{#if recipientSearch}<input name="search" type="hidden" value={recipientSearch} />{/if}');
    expect(scheduledEmailDetail).toContain('{#if currentRecipientPage > 1}<input name="page" type="hidden" value={currentRecipientPage} />{/if}');
    expect(scheduledEmailDetailServer).toContain('detailActionReturn');
    expect(scheduledEmailDetail).toContain('data.actionMessage');
    expect(scheduledEmailDetailServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(scheduledEmailDetailServer).toContain('throw redirect(303, detailActionReturn(params.id, form,');
    expect(scheduledEmailsServer).toContain('page: Number(url.searchParams.get');
    expect(scheduledEmailsServer).toContain("status: url.searchParams.get('status') ?? ''");
    expect(scheduledEmailsServer).toContain('localReturnTo');
    expect(scheduledEmailsServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(scheduledEmailsServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(scheduledEmailsServer).toContain('campaignActionReturn');
    expect(scheduledEmailsServer).toContain('throw redirect(303, campaignActionReturn(form,');
    expect(pageData).toContain('campaignsPage = repo.listCampaignsPage');
    expect(scheduledEmailDetailServer).not.toContain('before approving');
    expect(scheduledEmailDetailServer).not.toContain('approving this campaign');
    expect(scheduledEmailDetailServer).not.toContain("form.get('approved') === 'on'");
    expect(scheduledEmailDetailServer).toContain("form.get('scheduleMode') === 'ready'");
    expect(scheduledEmailDetailServer).not.toContain('Campaign updated.');
    expect(scheduledEmailDetailServer).toContain('Scheduled email updated.');
    expect(scheduledEmailsServer).not.toContain('Campaign schedule created.');
    expect(scheduledEmailsServer).toContain('Scheduled email created.');
    expect(scheduledEmailRepository).not.toContain('Campaign has sent deliveries and cannot be deleted.');
    expect(scheduledEmailRepository).toContain('Scheduled email has sent deliveries and cannot be deleted.');
    expect(scheduledEmailRepository).not.toContain('Campaign not found');
    expect(scheduledEmailRepository).not.toContain('Campaign delivery not found');
    expect(scheduledEmailRepository).toContain('Scheduled email not found');
    expect(scheduledEmailRepository).toContain('Scheduled email delivery not found');
    expect(readFileSync('src/lib/server/repository/templates.ts', 'utf8')).not.toContain('existing campaign');
    expect(readFileSync('src/lib/server/repository/templates.ts', 'utf8')).toContain('existing scheduled email');
    expect(settings).not.toContain('Blocks campaign sends');
    expect(settings).toContain('Blocks scheduled emails, direct email, SMTP tests, and test-mode reroutes until turned off.');
    expect(settings).toContain("sectionMatches('Reply Sync', ['imap inbox replies polling manual sync email replies'])");
    expect(settings).toContain('<p class="eyebrow">Replies</p>');
    expect(settings).not.toContain("sectionMatches('Reply Sync', ['imap inbox replies acknowledgements acknowledged polling manual sync email replies'])");
    expect(settings).not.toContain('<p class="eyebrow">Acknowledgements</p>');
    expect(settings).toContain("sectionMatches('Agent Access', ['ai assistant claude code local tools mcp token confirmation'])");
    expect(settings).toContain("sectionMatches('Agent Permissions', ['view edit import prepare schedule send settings confirmation workflow risk'])");
    expect(settings).not.toContain("sectionMatches('Agent Access', ['ai assistant claude code local tools mcp token approval'])");
    expect(settings).not.toContain("sectionMatches('Agent Permissions', ['view edit import prepare schedule send settings approval workflow risk'])");
  });

  test('keeps global send-due actions out of scheduled email detail', () => {
    const scheduledEmailDetail = readFileSync('src/routes/scheduled-emails/[id]/+page.svelte', 'utf8');
    const scheduledEmailDetailServer = readFileSync('src/routes/scheduled-emails/[id]/+page.server.ts', 'utf8');

    expect(scheduledEmailDetail).not.toContain('Send due now');
    expect(scheduledEmailDetail).not.toContain('?/sendDueNow');
    expect(scheduledEmailDetailServer).not.toContain('sendDueNow');
    expect(scheduledEmailDetailServer).not.toContain('manual_send_due');
    expect(scheduledEmailDetail).toContain('retryableRecipientCount');
    expect(scheduledEmailDetail).toContain('{#if retryableRecipientCount}');
    expect(scheduledEmailDetail).toContain('Queue selected for retry');
    expect(scheduledEmailDetail).not.toContain('Retry selected');
    expect(scheduledEmailDetail).toContain('No recipients need retrying.');
    expect(scheduledEmailDetail).not.toContain('No failed recipients to retry.');
  });

  test('formats technical delivery statuses before showing them to instructors', () => {
    const scheduledEmailDetail = readFileSync('src/routes/scheduled-emails/[id]/+page.svelte', 'utf8');
    const history = readFileSync('src/routes/history/+page.svelte', 'utf8');
    const contacts = readFileSync('src/routes/contacts/+page.svelte', 'utf8');
    const classDetail = readFileSync('src/routes/classes/[id]/+page.svelte', 'utf8');
    const classDetailServer = readFileSync('src/routes/classes/[id]/+page.server.ts', 'utf8');

    expect(scheduledEmailDetail).toContain('deliveryStatusLabel(recipient.status)');
    expect(history).toContain('messageStatusLabel(communication.status)');
    expect(contacts).toContain('messageStatusLabel(communication.status)');
    expect(classDetail).toContain('scheduledEmailDeliverySummary(campaign)');
    expect(classDetail).toContain('Search scheduled emails');
    expect(classDetail).toContain('data.scheduledCampaignsPage.total');
    expect(classDetail).toContain('classEmailsPageHref');
    expect(classDetail).toContain('classDetailReturnTo = $derived(classEmailsPageHref(currentClassEmailsPage))');
    expect(classDetail).toContain('href={`/scheduled-emails/${campaign.id}?returnTo=${encodeURIComponent(classDetailReturnTo)}`}');
    expect(classDetail).toContain('Page {currentClassEmailsPage} of {totalClassEmailsPages}');
    expect(classDetailServer).toContain('scheduledCampaignsPage: withVisibleScheduledEmailsPage(scheduledCampaignsPage)');
    expect(scheduledEmailDetail).not.toContain('{recipient.status}</span>');
    expect(history).not.toContain('{communication.status}</span>');
    expect(contacts).not.toContain('{communication.status}</span>');
    expect(classDetail).not.toContain('{campaign.pendingCount} pending');
    expect(classDetail).not.toContain('{campaign.failedCount} failed');
  });

  test('keeps Test Sends paginated and searchable', () => {
    const testSends = readFileSync('src/routes/test-audit/+page.svelte', 'utf8');
    const testSendsServer = readFileSync('src/routes/test-audit/+page.server.ts', 'utf8');
    const repository = readFileSync('src/lib/server/repository/communications.ts', 'utf8');

    expect(testSendsServer).toContain('listEmailTestAuditsPage');
    expect(testSends).toContain('Search test sends');
    expect(testSends).toContain("<p class=\"eyebrow\">Test Sends</p>");
    expect(testSends).toContain('Redirected test emails');
    expect(testSends).toContain('testAuditPageHref');
    expect(testSends).toContain('Page {currentTestAuditPage} of {totalTestAuditPages}');
    expect(testSends).not.toContain('Historical audit');
    expect(testSends).not.toContain('Redirected email audit');
    expect(repository).toContain('limit ? offset ?');
  });

  test('keeps Templates paginated and searchable', () => {
    const templates = readFileSync('src/routes/templates/+page.svelte', 'utf8');
    const templatesServer = readFileSync('src/routes/templates/+page.server.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');
    const repository = readFileSync('src/lib/server/repository/templates.ts', 'utf8');

    expect(templates).toContain('<h2>Email templates</h2>');
    expect(templates).not.toContain('Reusable personalized emails');
    expect(templates).toContain('<h3>Edit AI draft</h3>');
    expect(templates).not.toContain('Review AI draft');
    expect(templates).toContain('Search templates');
    expect(templates).toContain('templatesPageHref');
    expect(templates).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(templates).toContain('{#if data.returnTo}<input name="returnTo" type="hidden" value={data.returnTo} />{/if}');
    expect(templates).toContain('href={templatesClearHref}');
    expect(templates).toContain('templateListReturnTo');
    expect(templates).toContain('templateWorkflowReturnTo');
    expect(templates).toContain('data.actionMessage');
    expect(templates).toContain('{#if templatesSearch}<input name="search" type="hidden" value={templatesSearch} />{/if}');
    expect(templates).toContain('{#if currentTemplatesPage > 1}<input name="page" type="hidden" value={currentTemplatesPage} />{/if}');
    expect(templates).toContain('href={`/templates?action=create&returnTo=${encodeURIComponent(templateListReturnTo)}`}');
    expect(templates).toContain('href={`/templates?action=ai&returnTo=${encodeURIComponent(templateListReturnTo)}`}');
    expect(templates).toContain('href={`/templates?templateId=${template.id}&returnTo=${encodeURIComponent(templateListReturnTo)}`}');
    expect(templates).toContain("href={data.returnTo || '/templates'}");
    expect(templates).toContain('href={`/templates?action=ai&returnTo=${encodeURIComponent(templateWorkflowReturnTo)}`}');
    expect(templates).toContain('href={templateWorkflowReturnTo}');
    expect(templates).not.toContain('href="/templates?action=ai">Discard draft');
    expect(templates).not.toContain('href="/templates">Cancel');
    expect(templates).toContain('Page {currentTemplatesPage} of {totalTemplatesPages}');
    expect(templates).toContain('fields={variableFields}');
    expect(templates).not.toContain('<summary>Template fields</summary>');
    expect(templates).not.toContain('class="token-help"');
    expect(templates.indexOf('<div class="list">')).toBeLessThan(templates.indexOf('<div class="form-stack task-stack">'));
    expect(templates).not.toContain('<section class="band two-column">');
    expect(templatesServer).toContain('page: Number(url.searchParams.get');
    expect(templatesServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(templatesServer).toContain('templateActionReturn');
    expect(templatesServer).toContain('throw redirect(303, templateActionReturn(form,');
    expect(pageData).toContain('templatesPage = repo.listTemplatesPage');
    expect(repository).toContain('limit ? offset ?');
  });

  test('lets instructors reply to imported email replies from History', () => {
    const history = readFileSync('src/routes/history/+page.svelte', 'utf8');
    const contacts = readFileSync('src/routes/contacts/+page.svelte', 'utf8');
    const historyDetail = readFileSync('src/routes/history/[id]/+page.svelte', 'utf8');
    const historyServer = readFileSync('src/routes/history/+page.server.ts', 'utf8');
    const historyDetailServer = readFileSync('src/routes/history/[id]/+page.server.ts', 'utf8');
    const newEmail = readFileSync('src/routes/new-email/+page.svelte', 'utf8');
    const newEmailServer = readFileSync('src/routes/new-email/+page.server.ts', 'utf8');
    const pageData = readFileSync('src/lib/server/page-data.ts', 'utf8');

    expect(historyDetail).toContain('replyHref');
    expect(history).toContain('data.selectedSourceId');
    expect(history).toContain('params.set(\'sourceId\', data.selectedSourceId)');
    expect(history).toContain('data.selectedReplyStatus');
    expect(history).toContain("params.set('replyStatus', data.selectedReplyStatus)");
    expect(history).toContain('data.selectedStatus');
    expect(history).toContain("params.set('status', data.selectedStatus)");
    expect(history).toContain('data.selectedType');
    expect(history).toContain("params.set('type', data.selectedType)");
    expect(history).toContain("value: '', label: 'All email types'");
    expect(history).toContain("value: 'direct', label: 'Direct'");
    expect(history).toContain("value: 'scheduled', label: 'Scheduled'");
    expect(history).toContain("value: '', label: 'All delivery statuses'");
    expect(history).toContain("value: 'sent', label: 'Sent'");
    expect(history).toContain("value: 'failed', label: 'Failed'");
    expect(history).toContain('name="sourceId"');
    expect(history).toContain('Active filters');
    expect(history).toContain('This contact');
    expect(history).toContain('This scheduled email');
    expect(history).toContain('Needs a reply');
    expect(history).toContain("data.selectedStatus === 'failed' ? 'Failed emails' : 'Sent emails'");
    expect(history).toContain("data.selectedType === 'scheduled' ? 'Scheduled emails' : 'Direct emails'");
    expect(history).not.toContain('Filtered to selected contact');
    expect(history).not.toContain('Filtered to selected scheduled email');
    expect(history).not.toContain('Filtered to emails needing replies');
    expect(history).not.toContain('Filtered to {data.selectedStatus');
    expect(history).not.toContain('Filtered to {data.selectedType');
    expect(history).toContain('newEmailHref');
    expect(history).toContain('href={newEmailHref}');
    expect(history).toContain("params.set('returnTo', historyReturnTo)");
    expect(history).not.toContain('href="/new-email">New Email');
    expect(history).toContain('aria-label="Filter email history"');
    expect(history).toContain('aria-label="Filter email type"');
    expect(history).toContain('<span class="filter-label">Type</span>');
    expect(history).toContain('<span class="filter-label">Delivery</span>');
    expect(history).toContain('<span class="filter-label">Replies</span>');
    expect(history).toContain("value: '', label: 'All reply statuses'");
    expect(history).toContain("value: 'needs_reply', label: 'Needs reply'");
    expect(history).toContain('aria-label="Filter email delivery status"');
    expect(history).toContain('Clear filters');
    expect(history).toContain('historyReturnTo');
    expect(history).toContain("if (data.returnTo) params.set('returnTo', data.returnTo)");
    expect(history).toContain('{#if data.returnTo}<input type="hidden" name="returnTo" value={data.returnTo} />{/if}');
    expect(history).toContain('href={historyClearHref}');
    expect(history).toContain('returnTo=${encodeURIComponent(historyReturnTo)}');
    expect(history).toContain('href={`/history/${communication.id}?returnTo=${encodeURIComponent(historyReturnTo)}`}');
    expect(history).not.toContain('<div class="reply-list">');
    expect(history).not.toContain('{reply.snippet || reply.textBody}');
    expect(history).toContain('Reply');
    expect(history).toContain('Search sent, failed, and replied-to emails.');
    expect(history).toContain('replySummary({ replyCount: communication.replyCount, unhandledReplyCount: communication.unhandledReplyCount })');
    expect(contacts).toContain('replySummary({ replyCount: communication.replyCount, unhandledReplyCount: communication.unhandledReplyCount })');
    expect(history).not.toContain('communication.unreviewedReplyCount');
    expect(contacts).not.toContain('communication.unreviewedReplyCount');
    expect(readFileSync('src/lib/server/repository/types.ts', 'utf8')).not.toContain('unreviewedReplyCount');
    expect(history).not.toContain('compose workflow');
    expect(history).not.toContain('No reply yet');
    expect(history).not.toContain('Acknowledged');
    expect(history).not.toContain('<span class="pill good">Reviewed</span>');
    expect(history).not.toContain('new</span>');
    expect(history).toContain('replySummary({ replyCount: communication.replyCount, unhandledReplyCount: communication.unhandledReplyCount })');
    expect(history).toContain("value: 'needs_reply', label: 'Needs reply'");
    expect(historyDetail).toContain('<span class="pill good">Handled</span>');
    expect(historyDetail).not.toContain('Reply handled');
    expect(historyDetail).toContain('Mark handled');
    expect(historyDetail).toContain('Reply to the student or mark replies handled.');
    expect(historyDetail).toContain('<p class="eyebrow">Email detail</p>');
    expect(historyDetail).not.toContain('History detail');
    expect(historyDetail).toContain("communication.className || 'View class'");
    expect(historyDetail).not.toContain("communication.className || 'Class detail'");
    expect(historyDetail).toContain('href={data.returnTo || \'/history\'}');
    expect(historyDetail).toContain('data.actionMessage');
    expect(historyDetail).toContain('communication.classSessionId');
    expect(historyDetail).toContain('detailReturnTo');
    expect(historyDetail).toContain('href={`/contacts?contactId=${communication.contactId}&returnTo=${encodeURIComponent(detailReturnTo)}`}');
    expect(historyDetail).toContain('href={`/scheduled-emails/${communication.sourceId}?returnTo=${encodeURIComponent(detailReturnTo)}`}');
    expect(historyDetail).toContain('href={`/classes/${communication.classSessionId}?returnTo=${encodeURIComponent(detailReturnTo)}`}');
    expect(historyDetail).toContain("params.set('returnTo', detailReturnTo)");
    expect(historyDetailServer).toContain('localReturnTo');
    expect(historyDetailServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(historyDetail).toContain('?/markReplyHandled');
    expect(historyDetail).toContain('name="returnTo" value={data.returnTo}');
    expect(historyDetailServer).toContain('markReplyHandled');
    expect(historyDetailServer).toContain("actionMessage: url.searchParams.get('message') ?? ''");
    expect(historyDetailServer).toContain('detailActionReturn');
    expect(historyDetailServer).toContain('throw redirect(303, detailActionReturn(params.id, form,');
    expect(historyServer).not.toContain('markReplyHandled');
    expect(historyServer).toContain('localReturnTo');
    expect(historyServer).toContain("returnTo: localReturnTo(url.searchParams.get('returnTo') ?? '')");
    expect(historyServer).toContain("replyStatus: url.searchParams.get('replyStatus') || undefined");
    expect(historyServer).toContain("status: url.searchParams.get('status') || undefined");
    expect(historyServer).toContain("type: url.searchParams.get('type') || undefined");
    expect(historyDetail).not.toContain('Reply reviewed');
    expect(historyDetail).not.toContain('Mark reviewed');
    expect(historyDetail).not.toContain('mark replies reviewed');
    expect(historyDetail).not.toContain('reply.reviewedAt');
    expect(historyDetail).toContain('reply.handledAt');
    expect(readFileSync('src/lib/server/repository/types.ts', 'utf8')).not.toContain('reviewedAt: string');
    expect(readFileSync('src/lib/server/repository/types.ts', 'utf8')).toContain('handledAt: string');
    expect(historyDetail).not.toContain('markReplyReviewed');
    expect(historyDetailServer).not.toContain('markReplyReviewed');
    expect(historyDetailServer).not.toContain('markCommunicationReplyReviewed');
    expect(historyDetailServer).toContain('markCommunicationReplyHandled');
    expect(historyServer).not.toContain('markReplyReviewed');
    expect(readFileSync('src/lib/server/repository/index.ts', 'utf8')).not.toContain('markCommunicationReplyReviewed');
    expect(readFileSync('src/lib/server/repository/index.ts', 'utf8')).toContain('markCommunicationReplyHandled');
    expect(historyDetailServer).toContain('Reply marked handled.');
    expect(historyServer).not.toContain('Reply marked reviewed.');
    expect(historyDetailServer).not.toContain('Reply marked reviewed.');
    expect(history).toContain('<h3>Search history</h3>');
    expect(history).not.toContain('<h3>Email activity</h3>');
    expect(history).not.toContain('<h3>Email records</h3>');
    expect(history).toContain('<dl class="history-facts">');
    expect(history).toContain('<dt>Delivery</dt>');
    expect(history).toContain('<dt>Replies</dt>');
    expect(history).not.toContain('Every recorded email');
    expect(history).not.toContain('<div class="status-stack">');
    expect(historyDetail).toContain('/new-email?');
    expect(historyDetail).toContain('<div class="reply-list">');
    expect(historyDetail).toContain('{communication.body}');
    expect(newEmailServer).toContain("url.searchParams.get('subject')");
    expect(newEmailServer).toContain("url.searchParams.get('body')");
    expect(newEmailServer).toContain("url.searchParams.get('returnTo')");
    expect(newEmailServer).toContain('returnTo: localReturnTo');
    expect(newEmail).toContain('newEmailReturnTo');
    expect(newEmail).toContain('newEmailWorkflowReturnTo');
    expect(newEmail).toContain("params.set('subject', subject)");
    expect(newEmail).toContain("params.set('body', body)");
    expect(newEmail).toContain("params.set('returnTo', newEmailReturnTo)");
    expect(newEmail).toContain('href={newEmailReturnTo || \'/history\'}');
    expect(newEmail).toContain('name="returnTo"');
    expect(newEmailServer).toContain('directEmailOperationId');
    expect(newEmailServer).toContain("params.set('sourceId', sourceId)");
    expect(newEmailServer).toContain("params.set('returnTo', returnTo)");
    expect(newEmailServer).toContain('throw redirect(303, `/history?${params.toString()}`)');
    expect(pageData).toContain('prefillSubject');
    expect(pageData).toContain('prefillBody');
    expect(pageData).toContain('selectedReplyStatus');
    expect(newEmail).toContain('data.prefillSubject');
    expect(newEmail).toContain('data.prefillBody');
    expect(newEmail).not.toContain('<section class="band two-column">');
  });
});
